name: Action Release

on:
  push:
    paths:
      - 'actions/**'
    tags:
      - 'v*'
      - '*/v*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Action
        run: |
          if [ -f "${{ github.event.repository.name }}/action.yml" ]; then
            echo "✅ Action validation passed"
          else
            echo "❌ action.yml not found"
            exit 1
          fi

  release:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"* %s (%h)" > CHANGELOG.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false