name: Release

on:
  push:
    tags:
      - 'v*'
      - '*/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          # Generate root changelog
          echo "### Changelog" > CHANGES.md
          echo "" >> CHANGES.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"* %s" >> CHANGES.md
          
          # Update action changelog if tag matches action
          if [[ "${{ github.ref_name }}" =~ ^([^-]+)-v ]]; then
            ACTION_NAME="${BASH_REMATCH[1]}"
            if [ -d "actions/$ACTION_NAME" ]; then
              cat CHANGES.md >> "actions/$ACTION_NAME/CHANGELOG.md"
            fi
          fi
          
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          cat CHANGES.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
